import requests

# We use openstreetmap and overpass APIs
CAEN_BOUNDARY_RELATION = '149197'




'''
http://overpass-turbo.eu/#


/*
This has been generated by the overpass-turbo wizard.
The original search was:
“shop=* in Caen”
*/
[out:json][timeout:25];
// fetch area “Caen” to search in
{{geocodeArea:Caen}}->.searchArea;
// gather results
nwr["amenity"](area.searchArea);
// print results
out geom;
'''

def query():
  IS_JSON = True
  JSON_OR_XML = '.json' if IS_JSON  else ''

  r = requests.get(f'https://www.openstreetmap.org/api/0.6/relation/{CAEN_BOUNDARY_RELATION}{JSON_OR_XML}')
  print(r.text)




